### ISSUE TITLE
Race condition during testing

### ISSUE THREAD

**Issue by sledigabel** [Skyscanner/argocd-progressive-rollout#81]
Found this during CI from #78

https://github.com/Skyscanner/argocd-progressive-rollout/pull/78/checks?check_run_id=2563926011#step:6:115
The test `[It] should forward events for owned applications` is failing because (I think) the namespace is global but reset before each test, which could lead to a race condition where the namespace is changed during the reconcile loop and ends up being inconsistent.

The namespace is set here:
https://github.com/Skyscanner/argocd-progressive-rollout/blob/cb03eef8d637218632005b4266b5a4e47a37b55d/controllers/progressiverollout_controller_test.go#L48-L52

and the test is performed here:
https://github.com/Skyscanner/argocd-progressive-rollout/blob/cb03eef8d637218632005b4266b5a4e47a37b55d/controllers/progressiverollout_controller_test.go#L86-L108

**Comment by maruina** [comment]
I think this is the downside of using the controller client as @Smirl pointed out in https://github.com/Skyscanner/argocd-progressive-rollout/issues/73

Unfortunately I don't know how to make `requestsForApplicationChange` a function because of https://github.com/Skyscanner/argocd-progressive-rollout/pull/74#issuecomment-838394001

**Comment by sledigabel** [comment]
I assumed this was linked somehow.
i'll propose a way and feel free to destroy it or help me refactor

**Comment by sledigabel** [comment]
Closed via #83
